parameters:
#    coffee_closure.example.class: Galvani\CoffeeClosureBundle\Example

services:
#    coffee_closure.example:
#        class: %coffee_closure.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
